//authentication
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
//loading
export const LOADING_USER = 'LOADING_USER';
//user
export const SET_USER = 'SET_USER';
export const SET_UPDATE_USER = 'SET_UPDATE_USER';
export const SET_DELETE_USER = 'SET_DELETE_USER';
export const SET_DELETE_ERROR = 'SET_DELETE_ERROR';
export const SET_UPDATE_ERROR = 'SET_UPDATE_ERROR';

//profissional profile
export const SET_PPROFILES = 'SET_PPROFILES';
export const SET_PPROFILES_ERROR = 'SET_PPROFILES_ERROR';
export const SET_PPROFILE = 'SET_PPROFILE';
export const SET_PPROFILE_ERROR = 'SET_PPROFILE_ERROR';
export const SET_CREATE_PP = 'SET_CREATE_PP';
export const SET_CREATE_PP_ERROR = 'SET_CREATE_PP_ERROR';
export const SET_UPDATE_PP = 'SET_UPDATE_PP';
export const SET_UPDATE_PP_ERROR = 'SET_UPDATE_PP_ERROR';
export const SET_DELETE_PP = 'SET_DELETE_PP';
export const SET_DELETE_PP_ERROR = 'SET_DELETE_PP_ERROR';
